on: issue_comment

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
            const result = await github.pulls.listReviews({
                owner: "gravitational",
                repo: "gh-actions-poc",
                pull_number: context.payload.issue.number,
            })
            console.log(result)
            core.setFailed('Action failed')
