on: [pull_request, workflow_dispatch]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var r = Math.floor(Math.random() * 2)
            if (r == 0) {
                core.setFailed('Action failed')
            }
            #console.log(context)
            #if (context.eventName == "issue_comment") {
            #    core.setFailed('Action failed')
            #} else {
            #    github.pulls.requestReviewers({
            #      owner: "gravitational",
            #      repo: "gh-actions-poc",
            #      pull_number: context.payload.pull_request.number,
            #      reviewers: [
            #        "r0mant"
            #      ]
            #    })
            #}
