on: pull_request

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)
            console.log(context.payload)
            github.pulls.requestReviewers({
              owner: "gravitational",
              repo: "teleport",
              pull_number: context.payload.pull_request.number,
              reviewers: [
                "r0mant"
              ]
            })
