on: [pull_request]

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
      - run: go get -u github.com/google/go-github/v35
      - run: go run .github/workflows/hello.go
