on: [pull_request]

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.0'
      - name: setupdeps
        run: go get -u github.com/google/go-github/v35
      - name: runhello
        run: go run .github/workflows/hello.go
