on: [pull_request]

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.0'
      - run: go -v -u get github.com/google/go-github/v35
      - run: go run .github/workflows/hello.go
